---
url: "http://api.4everlearning-test.local.zaraffasoft.com/swagger/v1.json"
dom_id: "#swagger-ui"
validatorUrl: "https://online.swagger.io/validator"
oauth2RedirectUrl: "http://localhost:3200/oauth2-redirect.html"
